Preset 1:
  Name: ExampleValue
  XfadeAWidth: 10.0
  XfadeBWidth: 10.0
  XfadeCWidth: 10.0
  XfadeDWidth: 10.0
  MidiSetup: 16
  XfadeDCV: 1A
  Channel 1:
    ChannelMode: 0
    Pitch: 60.0
    Level: 6.0
    Pan: 1.0
    MixLevel: 6.0
    PlayMode: 1
    LoopMode: 2
    Reverse: 1
    Attack: 99.0
    Release: 99.0
    Bits: 32.0
    Aliasing: 100
    SpliceSmoothing: 1
    PMIndex: 1.0
    MixModIsFader: 1
    ZonesRT: 1
    XfadeGroup: D
    Zone 1:
      Sample: test.wav
      MinVoltage: 5.0
      MaxVoltage: 5.0
      LevelOffset: 6.0
      PitchOffset: 60.0
      Side: 1
      LoopMode: 2
      Bits: 32.0
      Smooth: 1
  Channel 2:
    ChannelMode: 3
    Pitch: 60.0
    Level: 6.0
    Pan: 1.0
    MixLevel: 6.0
    PlayMode: 1
    LoopMode: 2
    Reverse: 1
    Attack: 99.0
    Release: 99.0
    Bits: 32.0
    Aliasing: 100
    SpliceSmoothing: 1
    PMIndex: 1.0
    MixModIsFader: 1
    ZonesRT: 1
    XfadeGroup: D
    Zone 1:
      Sample: test.wav
      MinVoltage: 5.0
      MaxVoltage: 5.0
      LevelOffset: 6.0
      PitchOffset: 60.0
      Side: 1
      LoopMode: 2
      Bits: 32.0
      Smooth: 1
