Preset 1:
  Name: ExampleValue
  XfadeAWidth: 0.01
  XfadeBWidth: 0.01
  XfadeCWidth: 0.01
  XfadeDWidth: 0.01
  MidiSetup: 1
  XfadeACV: 1A
  Channel 1:
    ChannelMode: 0
    Pitch: -96.0
    Level: -90.0
    Pan: -1.0
    MixLevel: -90.0
    PlayMode: 0
    LoopMode: 0
    Reverse: 0
    Attack: 0.0
    Release: 0.0
    Bits: 1.0
    Aliasing: 0
    SpliceSmoothing: 0
    PMIndex: 0.0
    MixModIsFader: 0
    ZonesRT: 0
    XfadeGroup: A
    Zone 1:
      Sample: test.wav
      MinVoltage: -5.0
      MaxVoltage: -5.0
      LevelOffset: -90.0
      PitchOffset: -96.0
      Side: 0
      LoopMode: 0
      Bits: 1.0
      Smooth: 0
  Channel 2:
    ChannelMode: 0
    Pitch: -96.0
    Level: -90.0
    Pan: -1.0
    MixLevel: -90.0
    PlayMode: 0
    LoopMode: 0
    Reverse: 0
    Attack: 0.0
    Release: 0.0
    Bits: 1.0
    Aliasing: 0
    SpliceSmoothing: 0
    PMIndex: 0.0
    MixModIsFader: 0
    ZonesRT: 0
    XfadeGroup: A
    Zone 1:
      Sample: test.wav
      MinVoltage: -5.0
      MaxVoltage: -5.0
      LevelOffset: -90.0
      PitchOffset: -96.0
      Side: 0
      LoopMode: 0
      Bits: 1.0
      Smooth: 0
